# Configuration for Gap Prediction CNN
# Author: Oussama GUELFAA
# Date: 10 - 01 - 2025

model:
  name: "GapPredictionCNN"
  type: "1D_CNN_Residual"
  input_size: 1000
  output_size: 1
  
architecture:
  conv_layers:
    - channels: 64
      kernel_size: 7
      stride: 2
      padding: 3
    - channels: 128
      kernel_size: 5
      stride: 2
      padding: 2
    - channels: 256
      kernel_size: 3
      stride: 2
      padding: 1
    - channels: 512
      kernel_size: 3
      stride: 2
      padding: 1
  
  residual_blocks:
    - input_channels: 128
      output_channels: 128
    - input_channels: 256
      output_channels: 256
  
  dense_layers:
    - size: 256
      dropout: 0.3
    - size: 128
      dropout: 0.2
    - size: 1

training:
  batch_size: 32
  epochs: 200
  learning_rate: 0.001
  optimizer: "Adam"
  loss_function: "MSE"
  early_stopping:
    patience: 20
    min_delta: 0.0001
  
data:
  train_split: 0.8
  val_split: 0.2
  normalization: "StandardScaler"
  input_features: 1000
  target_parameter: "gap"
  
paths:
  data_file: "../data_generation/all_banque_new_24_01_25_NEW_full.mat"
  model_save: "models/best_model.pth"
  plots_dir: "plots/"
  results_dir: "results/"
