# Configuration for TensorFlow/Keras Alternative
# Author: Oussama GUELFAA
# Date: 10 - 01 - 2025

experiment:
  name: "TensorFlow_Keras_Alternative"
  description: "Alternative TensorFlow/Keras avec architecture Dense optimisée"
  version: "tensorflow"

model:
  name: "TensorFlowRegressor"
  type: "Dense_Sequential_Keras"
  input_size: 1000
  output_size: 2
  
architecture:
  # Architecture Dense spécifiée dans les mémoires
  dense_layers:
    - size: 512
      activation: "relu"
      dropout: 0.2
    - size: 256
      activation: "relu"
      dropout: 0.2
    - size: 128
      activation: "relu"
      dropout: 0.2
    - size: 64
      activation: "relu"
      dropout: 0.2
    - size: 2
      activation: "linear"
  
  # Régularisation
  batch_normalization: true
  kernel_regularizer: "l2"
  l2_lambda: 0.0001

training:
  # Paramètres TensorFlow/Keras
  batch_size: 32
  epochs: 200
  learning_rate: 0.001
  optimizer: "Adam"
  
  # Loss et métriques
  loss_function: "mse"
  metrics: ["mae", "mse"]
  
  # Callbacks Keras
  callbacks:
    early_stopping:
      enable: true
      monitor: "val_loss"
      patience: 20
      restore_best_weights: true
    
    reduce_lr:
      enable: true
      monitor: "val_loss"
      factor: 0.5
      patience: 10
      min_lr: 0.00001
    
    model_checkpoint:
      enable: true
      filepath: "models/tensorflow_best_model.h5"
      monitor: "val_loss"
      save_best_only: true

data:
  # Préparation données TensorFlow
  normalization: "StandardScaler"
  validation_split: 0.2
  shuffle: true
  
  # Augmentation de données
  data_augmentation:
    enable: false
    noise_factor: 0.01

evaluation:
  # Métriques d'évaluation
  metrics:
    - "r2_score"
    - "mean_squared_error"
    - "mean_absolute_error"
    - "root_mean_squared_error"
  
  performance_targets:
    r2_L_ecran: 0.95
    r2_gap: 0.8
    r2_global: 0.85

tensorflow_specific:
  # Configurations spécifiques TensorFlow
  mixed_precision: false
  distribute_strategy: false
  
  # Optimisations
  jit_compile: false
  use_multiprocessing: true
  workers: 4
  
  # Monitoring
  tensorboard:
    enable: false
    log_dir: "logs/"
  
  # Sauvegarde
  save_format: "h5"  # ou "tf"

paths:
  data_file: "../data_generation/all_banque_new_24_01_25_NEW_full.mat"
  models_dir: "models/"
  plots_dir: "plots/"
  results_dir: "results/"
  logs_dir: "logs/"

visualization:
  generate_plots: true
  plot_types:
    - "training_history"
    - "model_architecture"
    - "predictions_scatter"
    - "residuals_analysis"
    - "keras_model_plot"

expected_results:
  # Résultats TensorFlow attendus
  performance:
    r2_global: "> 0.85"
    convergence: "< 150 epochs"
    training_time: "< 15 minutes"
    keras_compatibility: "full"
  
  advantages:
    - "API Keras intuitive"
    - "Callbacks automatiques"
    - "Visualisation TensorBoard"
    - "Sauvegarde native .h5"
