# Configuration for Ultra Specialized Regressor
# Author: Oussama GUELFAA
# Date: 10 - 01 - 2025

experiment:
  name: "Ultra_Specialized_Regressor"
  description: "Architecture ultra-spécialisée avec focus maximal sur gap et ensemble training"
  version: "ultra"

model:
  name: "UltraSpecializedRegressor"
  type: "Ultra_Specialized_Ensemble"
  input_size: 600
  output_size: 2
  
architecture:
  # Feature extractor plus profond
  feature_extractor:
    layers:
      - size: 1024
        batch_norm: true
        dropout: 0.3
      - size: 512
        batch_norm: true
        dropout: 0.2
      - size: 256
        batch_norm: true
        dropout: 0.15
      - size: 128
        batch_norm: true
        dropout: 0.1
  
  # Tête L_ecran simple (signal fort)
  L_ecran_head:
    layers:
      - size: 32
        dropout: 0.0
      - size: 1
  
  # Tête gap ultra-spécialisée
  gap_head:
    feature_enhancer:
      layers:
        - size: 256
          batch_norm: true
          dropout: 0.2
        - size: 128
          batch_norm: true
          dropout: 0.1
    
    dual_attention:
      attention_1:
        size: 128
        activation: "tanh"
      attention_2:
        size: 128
        activation: "sigmoid"
    
    final_layers:
      - size: 96
        dropout: 0.05
      - size: 64
        dropout: 0.02
      - size: 32
        dropout: 0.0
      - size: 1

training:
  # Paramètres ultra-optimisés
  batch_size: 16  # Plus petit pour focus
  epochs: 200
  learning_rate: 0.0001  # Plus lent pour stabilité
  optimizer: "AdamW"
  weight_decay: 0.0001
  
  # Loss ultra-pondérée
  loss_function: "UltraWeightedMSE"
  gap_weight: 50.0  # Poids extrême pour gap
  L_ecran_weight: 1.0
  
  # Early stopping strict
  early_stopping:
    patience: 30
    min_delta: 0.00001
    restore_best_weights: true
  
  # Scheduler agressif
  lr_scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.3
    patience: 15
    min_lr: 0.000001

ensemble_training:
  enable: true
  n_models: 3
  gap_weights: [30, 50, 70]  # Différents poids pour diversité
  voting_strategy: "weighted_average"
  
data_preprocessing:
  # Prétraitement ultra-optimisé
  label_rounding:
    enable: true
    decimals: 3
  
  experimental_focus:
    enable: true
    gap_range: [0.025, 0.517]
    strict_filtering: true
  
  profile_truncation:
    enable: true
    truncate_to: 600
    
  separate_normalization:
    enable: true
    robust_scaling: false  # StandardScaler standard

evaluation:
  # Évaluation ultra-stricte
  tolerance_evaluation:
    enable: true
    tolerance_L: 0.3  # Plus strict
    tolerance_gap: 0.005  # Très strict
  
  performance_targets:
    r2_L_ecran: 0.98
    r2_gap: 0.85  # Plus ambitieux
    tolerance_accuracy_gap: 0.95

advanced_features:
  # Fonctionnalités ultra-avancées
  dual_attention:
    enable: true
    combination_strategy: "multiplicative"
  
  feature_enhancement:
    enable: true
    enhancement_layers: 2
  
  gradient_clipping:
    enable: true
    max_norm: 0.5  # Plus strict
  
  weight_initialization:
    type: "xavier_uniform"
    gain: 1.0

monitoring:
  log_frequency: 5
  detailed_logging: true
  save_all_models: true  # Pour ensemble
  
paths:
  data_file: "../data_generation/all_banque_new_24_01_25_NEW_full.mat"
  models_dir: "models/"
  plots_dir: "plots/"
  results_dir: "results/"

expected_results:
  # Résultats ultra-ambitieux
  L_ecran_prediction:
    r2_score: "> 0.98"
    rmse: "< 0.05 µm"
    tolerance_accuracy: "> 98%"
  
  gap_prediction:
    r2_score: "> 0.85"
    rmse: "< 0.02 µm"
    tolerance_accuracy: "> 95%"
  
  ensemble_performance:
    improvement_over_single: "> 5%"
    stability: "high"
    robustness: "excellent"
